from datetime import datetime
from pathlib import Path

from primordial_llm.data.models import ChatSessionState, ReplicationBlueprint, RuntimeContext


class PrimordialReplicationEngine:
    """Clones future Primor organs as concrete implementation blueprints."""

    def __init__(self, runtime: RuntimeContext) -> None:
        self.runtime = runtime

    def seed_missing_organs(self, session: ChatSessionState) -> None:
        for blueprint in self._default_blueprints():
            session.replication.register(blueprint)
        if session.replication.blueprints:
            session.replication.latest_report_path = self._persist_blueprints(session.replication.blueprints)

    def _persist_blueprints(self, blueprints: list[ReplicationBlueprint]) -> Path:
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        report_path = self.runtime.paths.reports_root / f"replication-blueprints-{timestamp}.md"
        lines = [
            "# Primor Replication Blueprints",
            "",
            "These blueprints were generated by the Replication Organ.",
            "",
        ]
        for blueprint in blueprints:
            lines.extend(
                [
                    f"## {blueprint.organ_name}",
                    "",
                    f"- Target module: `{blueprint.target_module}`",
                    f"- Role: {blueprint.role}",
                    f"- Status: {blueprint.status}",
                    f"- Planned interfaces: {', '.join(blueprint.planned_interfaces)}",
                    f"- Dependencies: {', '.join(blueprint.dependencies)}",
                    f"- Source nutrients: {', '.join(blueprint.source_nutrients)}",
                    "",
                ]
            )
        report_path.write_text("\n".join(lines), encoding="utf-8")
        return report_path

    @staticmethod
    def _default_blueprints() -> list[ReplicationBlueprint]:
        return [
            ReplicationBlueprint(
                organ_name="Replacement Tracker Organ",
                target_module="primordial_llm/data/replacement_tracker.py",
                role="Track which host territories remain active, scaffolded, demoted, or fully replaced.",
                planned_interfaces=["mark_region", "summarize_occupation", "load_tracker_state"],
                dependencies=["primordial_llm/data/models.py", "llm_sandbox/memory/reports"],
                source_nutrients=["MISSING_ORGANS_REGISTRY.md", "DIGESTION_LEDGER.md"],
            ),
            ReplicationBlueprint(
                organ_name="Substrate Demotion Organ",
                target_module="primordial_llm/output/substrate_adapter.py",
                role="Subordinate the absorbed runtime into an explicit substrate adapter with no architectural authority.",
                planned_interfaces=["load_substrate", "generate_from_packet"],
                dependencies=["primordial_llm/output/model_runtime.py", "primordial_llm/process/context_assembly.py"],
                source_nutrients=["PRIMORDIAL_ANATOMY_INDEX.md", "PRIMORDIAL_DIGESTION_MAP.md"],
            ),
            ReplicationBlueprint(
                organ_name="Memory Consolidation Organ",
                target_module="primordial_llm/process/memory_consolidation.py",
                role="Convert active traces and reports into stable Primor memory artifacts after important turns.",
                planned_interfaces=["consolidate_session", "emit_memory_note", "update_identity_links"],
                dependencies=["primordial_llm/data/models.py", "llm_sandbox/memory/short_term", "llm_sandbox/memory/long_term"],
                source_nutrients=["PRIMOR_CONTINUITY_LOG.md", "llm_sandbox/memory"],
            ),
        ]
